name: bharatekrishi
description: bharatekrishi app

publish_to: 'none'

version: 1.0.14+14

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  http: ^1.1.0
  flutter_inset_box_shadow: ^1.0.8
  curved_navigation_bar: ^1.0.3
  fluttertoast: ^8.2.2
  toggle_switch: ^2.1.0
  google_maps_flutter: ^2.5.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^10.1.0
  flutter_share: ^2.0.0
  permission_handler: ^11.0.0
  geocoding: ^2.1.0
  url_launcher: ^6.1.14
  flutter_barcode_scanner: ^2.0.0
  flutter_native_contact_picker: ^0.0.4
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.5.3
  flutter_polyline_points:
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  maps_toolkit: ^3.0.0
  another_flushbar: ^1.12.30
  intl: ^0.18.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.3

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/livem/